### ISSUE TITLE
Searcher isn't starting

### ISSUE THREAD

**Issue by 9ce59b18** [SieBRUM/minecraft-server-discovery#1]
I launched the thing with "ng serve" but the searcher isn't starting, I refresch after hours..... Nothing :/ Did I something wrong or is it a bug

**Comment by SieBRUM** [comment]
The front-end is just to visualise the data. It does not gather data.
The backend does both the scanning ([MasscanWrapper](https://github.com/SieBRUM/minecraft-server-discovery/tree/main/backend/MasscanWrapper)) and serving the data ([MinecraftServerDiscoveryApi](https://github.com/SieBRUM/minecraft-server-discovery/tree/main/backend/MinecraftServerDiscoveryApi)).

You also need a database to save this information somewhere. The connection string to this database should be located in your env variables. (see https://github.com/SieBRUM/minecraft-server-discovery/blob/main/backend/MinecraftServerDiscoveryApi/Contexts/DatabaseContext.cs#L20)

Almost everything I just said here is documented in the README.md (the very very first file you see when you open this repo)
