### ISSUE TITLE
How to start scanning?

### ISSUE THREAD

**Issue by Sectorfive03** [SieBRUM/minecraft-server-discovery#6]
I installed docker and run the docker compose up, it started the GUI on the localhost port 80 which I can access. but I don't understand how do I start scanning? there's no website or anything on the port 5000 or 500, I tried both. and the README.MD doesn't explain this part of the process well.

**Comment by SieBRUM** [comment]
The runner has to be executed seperately. As of right now, it only supports windows out of the box.

If you want to run it, you have to build it and run the executable.

**Comment by Bensonheimer992** [comment]
@SieBRUM  where can i download the scanner ?

**Comment by SieBRUM** [comment]
> @SieBRUM where can i download the scanner ?

The scanner can be found here https://github.com/SieBRUM/minecraft-server-discovery/tree/main/backend/MasscanWrapper

You have to build it yourself.

**Comment by Bensonheimer992** [comment]
@SieBRUM  i have this error while Building : 
Starting scanning process on range 0.0.0.0/0!
Unhandled exception. System.ComponentModel.Win32Exception (2): Das System kann die angegebene Datei nicht finden.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MasscanWrapper.Program.CreateAndStartScanningProcess(String fileName, String ipRange, String rateLimit) in C:\Users\alex\Documents\Git\minecraft-server-discovery\backend\MasscanWrapper\Program.cs:line 175
   at MasscanWrapper.Program.Main(String[] args) in C:\Users\alex\Documents\Git\minecraft-server-discovery\backend\MasscanWrapper\Program.cs:line 90

**Comment by SieBRUM** [comment]
> @SieBRUM i have this error while Building : Starting scanning process on range 0.0.0.0/0! Unhandled exception. System.ComponentModel.Win32Exception (2): Das System kann die angegebene Datei nicht finden. at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at MasscanWrapper.Program.CreateAndStartScanningProcess(String fileName, String ipRange, String rateLimit) in C:\Users\alex\Documents\Git\minecraft-server-discovery\backend\MasscanWrapper\Program.cs:line 175 at MasscanWrapper.Program.Main(String[] args) in C:\Users\alex\Documents\Git\minecraft-server-discovery\backend\MasscanWrapper\Program.cs:line 90

It says it cannot find your `masscan.exe` executable. The wrapper defaults to your desktop if you do not answer the question "**Location of masscanner?.**" Do you have `masscan.exe` on your device, and if so, is it on your desktop? If it is not on your desktop, you have to supply the path to the executable.

Headsup: Im pretty sure masscan.exe requires NpCap to be installed on your machine.

For reference, see https://github.com/SieBRUM/minecraft-server-discovery/blob/main/backend/MasscanWrapper/Program.cs#L22

**Comment by Bensonheimer992** [comment]
i thought id would build the executable

**Comment by Bensonheimer992** [comment]
@SieBRUM  now it says this : Unhandled exception. System.ComponentModel.Win32Exception (5): Zugriff verweigert
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MasscanWrapper.Program.CreateAndStartScanningProcess(String fileName, String ipRange, String rateLimit) in C:\Users\alex\Documents\Git\minecraft-server-discovery\backend\MasscanWrapper\Program.cs:line 175
   at MasscanWrapper.Program.Main(String[] args) in C:\Users\alex\Documents\Git\minecraft-server-discovery\backend\MasscanWrapper\Program.cs:line 90

**Comment by Bensonheimer992** [comment]
i htink that means no perms right ?

**Comment by SieBRUM** [comment]
> i thought id would build the executable

No, masscan is a separate executable which I do not own. It can be found here if you want to build it yourself: https://github.com/robertdavidgraham/masscan or compiled versions can be found here https://github.com/Arryboom/MasscanForWindows .

> i htink that means no perms right ?

Consider running the application as an administrator if you have permission issues.

**Comment by Bensonheimer992** [comment]
Yeah i downloaded the exe

**Comment by Bensonheimer992** [comment]
@SieBRUM i downloaded the exe

**Comment by Bensonheimer992** [comment]
@SieBRUM  is there any way to run the scanner on linux ?

**Comment by SieBRUM** [comment]
> @SieBRUM is there any way to run the scanner on linux ?

No.

**Comment by Bensonheimer992** [comment]
@SieBRUM  because if i run it on my machine i can't acces the internet at all but if i stop the scanner i can reach google for example

**Comment by SieBRUM** [comment]
> @SieBRUM because if i run it on my machine i can't acces the internet at all but if i stop the scanner i can reach google for example

I suggest playing with the ratelimiting (the wrapper asks how you want your stuff ratelimited when you execute it). Otherwise, I dont know and its probably an issue with masscan and/or your network.

**Comment by Bensonheimer992** [comment]
@SieBRUM  now there are some entrys in the database but they are not shown on the webpage

**Comment by SieBRUM** [comment]
Please create a separate issue and provide as much info as you can (screenshots, logs, versions etc),
