### ISSUE TITLE
Servers not showing on the Website

### ISSUE THREAD

**Issue by Bensonheimer992** [SieBRUM/minecraft-server-discovery#7]
Docker Logs : webapp-container  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
webapp-container  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
webapp-container  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
webapp-container  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
webapp-container  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
webapp-container  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
webapp-container  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
webapp-container  | /docker-entrypoint.sh: Configuration complete; ready for start up
webapp-container  | 192.168.81.125 - - [17/Mar/2024:12:21:09 +0000] "GET /home HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
webapp-container  | 192.168.81.125 - - [17/Mar/2024:12:21:31 +0000] "GET /app HTTP/1.1" 200 7728 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
webapp-container  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
webapp-container  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
webapp-container  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
webapp-container  | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
webapp-container  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
webapp-container  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
webapp-container  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
webapp-container  | /docker-entrypoint.sh: Configuration complete; ready for start up
api-container     | warn: 03/17/2024 12:21:05.014 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure)
api-container     |       Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
api-container     | info: 03/17/2024 12:21:05.207 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
api-container     |       Entity Framework Core 5.0.17 initialized 'DatabaseContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: ServerVersion 8.0.36-mysql SensitiveDataLoggingEnabled DetailedErrorsEnabled
api-container     | info: 03/17/2024 12:21:05.391 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
api-container     |       Executed DbCommand (25ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
api-container     |       SELECT CASE WHEN COUNT(*) = 0 THEN FALSE ELSE TRUE END
api-container     |       FROM information_schema.tables
api-container     |       WHERE table_type = 'BASE TABLE' AND table_schema = 'MCServerDiscovery'
api-container     | info: Microsoft.Hosting.Lifetime[0]
api-container     |       Now listening on: http://[::]:5000
api-container     | info: Microsoft.Hosting.Lifetime[0]
api-container     |       Application started. Press Ctrl+C to shut down.
api-container     | info: Microsoft.Hosting.Lifetime[0]
api-container     |       Hosting environment: Production
api-container     | info: Microsoft.Hosting.Lifetime[0]
api-container     |       Content root path: /app
api-container     | info: Microsoft.Hosting.Lifetime[0]
api-container     |       Application is shutting down...
api-container     | warn: 03/17/2024 17:28:13.062 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure)
api-container     |       Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
api-container     | info: 03/17/2024 17:28:13.192 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
api-container     |       Entity Framework Core 5.0.17 initialized 'DatabaseContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: ServerVersion 8.0.36-mysql SensitiveDataLoggingEnabled DetailedErrorsEnabled
api-container     | info: 03/17/2024 17:28:13.459 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
api-container     |       Executed DbCommand (24ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
api-container     |       SELECT CASE WHEN COUNT(*) = 0 THEN FALSE ELSE TRUE END
api-container     |       FROM information_schema.tables
api-container     |       WHERE table_type = 'BASE TABLE' AND table_schema = 'MCServerDiscovery'
api-container     | info: Microsoft.Hosting.Lifetime[0]
api-container     |       Now listening on: http://[::]:5000
api-container     | info: Microsoft.Hosting.Lifetime[0]
api-container     |       Application started. Press Ctrl+C to shut down.
api-container     | info: Microsoft.Hosting.Lifetime[0]
api-container     |       Hosting environment: Production
api-container     | info: Microsoft.Hosting.Lifetime[0]
api-container     |       Content root path: /app

MySQL : 
![grafik](https://github.com/SieBRUM/minecraft-server-discovery/assets/101340634/131d784f-f679-4bee-8e76-60fef767eba5)
![grafik](https://github.com/SieBRUM/minecraft-server-discovery/assets/101340634/cd0c2985-f0bb-41e1-ba35-e215a6c35bf5)

Website : 
![grafik](https://github.com/SieBRUM/minecraft-server-discovery/assets/101340634/a9480da5-08fe-4196-823a-f97b2d134428)

**Comment by SieBRUM** [comment]
Hey, thank you for providing all this info.

It looks like the scanner, API and database are functioning correctly, so I suppose the front-end is doing some weirdness.

Would you mind doing the following:
1. Start the database, API and website
2. Open the website
3.  Press F12 (open console)
4. reload the website
5. Send a screenshot of the 'console'  and 'network' tabs within the F12 (console) window

**Comment by Bensonheimer992** [comment]
![grafik](https://github.com/SieBRUM/minecraft-server-discovery/assets/101340634/ce8f3439-bb34-496d-87c9-2cc4953c9879)

**Comment by SieBRUM** [comment]
That's odd. The line https://github.com/SieBRUM/minecraft-server-discovery/blob/main/backend/MinecraftServerDiscoveryApi/Startup.cs#L55 should prevent this from happening. I also cannot replicate this on my Windows and Ubuntu VM. Which browser are you using?


Can you remove the line https://github.com/SieBRUM/minecraft-server-discovery/blob/main/backend/MinecraftServerDiscoveryApi/Startup.cs#L56 (so remove the `.AllowCredentials());`) and rebuild the project + fully rebuild the docker container? Does that fix the issue?

**Comment by Bensonheimer992** [comment]
No this doesn't work

**Comment by Bensonheimer992** [comment]
i changed the Production URL in the website config to the server ip:5000 instead of localhost:5000 because in docker localhost is the webapp-container itself

**Comment by Bensonheimer992** [comment]
now it works

**Comment by SieBRUM** [comment]
> i changed the Production URL in the website config to the server ip:5000 instead of localhost:5000 because in docker localhost is the webapp-container itself

Thats not true but im happy it works! :)

**Comment by Bensonheimer992** [comment]
yes thats true if you use localhost in a docker container it points to itself
